### PR TITLE
fix(dcellar-web-ui): disable selection of SPs with invalid status in …

### PR DESCRIPTION
**Pull request by devinxl**
…SPSelector

## Types of changes

- [ ] Docs refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [x] I have updated changeset
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by aiden-cao — APPROVED** [review]

**Review by Crissmael — COMMENTED** [review]
First change log

**Pull request merged**
